---
services:
  morning:
    image: ${TEST_IMAGE}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:5000/ping"]
      interval: 5s
      timeout: 5s
      retries: 12
    env_file:
      - .env
    restart: always
    expose:
      - "5000"
    ports:
      - 5000:5000
    depends_on:
      - redis
      - selenium
  redis:
    restart: always
    image: "redis:alpine"
    expose:
      - "6379"
    volumes:
      - redis-data:/var/lib/redis
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 12
  selenium:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 5s
      timeout: 5s
      retries: 12
    shm_size: "2gb"
    image: selenium/standalone-chrome
    env_file:
      - .env
    restart: always
    expose:
      - "4444"
volumes:
  redis-data:
