apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: ilpost-scraper
build:
  artifacts:
    - image: ilpostscraper
      sync:
        infer:
          - src/*
  local: {}
manifests:
  rawYaml:
    - k8s/secret.yaml
    - k8s/ilpost-scraper-default-networkpolicy.yaml
    - k8s/ilpost-scraper-deployment.yaml
    - k8s/ilpost-scraper-service.yaml
    - k8s/redis-data-persistentvolumeclaim.yaml
    - k8s/redis-deployment.yaml
    - k8s/redis-service.yaml
    - k8s/selenium-deployment.yaml
    - k8s/selenium-service.yaml
portForward:
  - resourceType: deployment
    resourceName: ilpostscraper
    port: 5000
  - resourceType: deployment
    resourceName: selenium
    port: 4444
