apiVersion: v1
kind: Service
metadata:
  name: {{ include "ilpostpodcastscraper.fullname" . }}-redis
  labels:
    app: redis
    group: ilpostscraper
  {{- include "ilpostpodcastscraper.labels" . | nindent 4 }}
spec:
  type: {{ .Values.redis.type }}
  selector:
    app: redis
    group: ilpostscraper
  {{- include "ilpostpodcastscraper.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.redis.ports | toYaml | nindent 2 -}}