apiVersion: v1
kind: Service
metadata:
  name: {{ include "ilpostpodcastscraper.fullname" . }}-scraper
  labels:
    app: scraper
    group: ilpostscraper
  {{- include "ilpostpodcastscraper.labels" . | nindent 4 }}
spec:
  type: {{ .Values.scraper.type }}
  selector:
    app: scraper
    group: ilpostscraper
  {{- include "ilpostpodcastscraper.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.scraper.ports | toYaml | nindent 2 -}}